[package]
name = "core86"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.2.1"
codepage-437 = "0.1.0"
intbits = "0.2.0"
num_enum = "0.6.1"
ncurses = "5.101.0"
iced-x86 = "1.18.0"
